/*
 * This source file was generated by the Gradle 'init' task
 */
package taller5;

public class App {
    
    public static void main(String[] args) {
        
        try {
            
        } 
        
        catch (Exception e) {
            // TODO: handle exception
        }
    }


    /*
    
        1.	Desarrolle un algoritmo e impleméntelo en Java que: le pida al usuario un número entero positivo 
        entre 1000 y 9999. En un ciclo genere números de manera aleatoria y cuente los intentos que hizo antes 
        de hallar el número exactamente.
        
    
    */ 
public static int Intentos_numeros(int numero){
        try {
            final int mil=1000, nueve_mil=9999, mil_uno=1001;
            int aleatorio=0, contador=0;

            if(numero >= mil && numero<= nueve_mil){

                do {
                    aleatorio= (int) (Math.random()*(nueve_mil-mil)+mil_uno);
                    contador++;
                    
                } while (aleatorio != numero);
                
            } else
                return 0;

            return contador;

        } catch (Exception e) {
            return -1;
        }
    }



    /* 
     
        2.	Se requiere una función en java que simule las ventas de tres años para un almacén. Para cada año, deberá generar 
        un aleatorio para cada mes hasta completar los 12 meses. La función se llamará Simular_ventas, y debe retornar un String 
        al final que muestre las ventas de cada año, así:
        
            Año 1
            Ventas Mes 1: $##.###.###
            :
            Ventas Mes 12: $##.###.###
            Total ventas Año 1:  $##.###.###
            
            Año 2
            Ventas Mes 1: $##.###.###
            :
            Ventas Mes 12: $##.###.###
            Total ventas Año 2: $##.###.###
            
            Año 3
            Ventas Mes 1: $##.###.###
            :
            Ventas Mes 12: $##.###.###

            Total ventas Año 3: $##.###.###
            
            Investigue sobre la clase DecimalFormat para mostrar bien la salida. 
            import java.text.DecimalFormat;
            DecimalFormat form_pesos = new DecimalFormat("$#,###.00");

        
      
    */
public static String Simular_ventas(){
        try {
            final byte tres=3, doce=12;
            double total=0;
            double aleatorio=0;
            String respuesta="", numero_decimal="", numero_total="";

            for (byte ano=1; ano <= tres; ano++) {
                respuesta += "Año " + ano + "\n";

                for (byte mes=1; mes <=doce; mes ++) {
                    DecimalFormat formato= new DecimalFormat("$##,###.###");
                    aleatorio=(Math.random()*(99999-0)+1);
                    numero_decimal= formato.format(aleatorio);

                    respuesta += "Venta Mes "+ mes+ ": "+ numero_decimal+ "\n";

                    total+= aleatorio;
                    DecimalFormat nuevo= new DecimalFormat("$##,###.###");
                    numero_total= nuevo.format(total);
                    
                }
                respuesta+= "Total Ventas Año "+ ano+ ": " + numero_total+ "\n";
            }

            return respuesta;
        } catch (Exception e) {
            return "ERROR"+e;
        }
    }
    

    /*  
     
        3.	En una fábrica se tiene el siguiente patrón de empaque: En una estiba(o pallet) caben 16  cajas y en cada caja, 
        caben 30 bombillas. Desarrolle una función que se llame: Calcular_empaque que: reciba como argumento la cantidad de 
        bombillas que se deben empacar y a partir de allí: calcule cuántas cajas necesita, cuántas estibas o pallets necesita. 
        Luego escriba lo siguiente: 

        Para ### bombillas, se necesitan ## cajas y ## pallets. Se quedan ### bombillas sin empacar. Se empacará así:

        Pallet 1 --> Caja1, Caja2……,Caja16
        Pallet2 -->  Caja17, Caja18…..Caja 32
        .
        Pallet n -- > Caja m, caja m+1…..
        
        La función retornará un texto, con la información anterior. Pruebe la función llamándola desde el programa principal: solicite al usuario el número de bombillas e invoque la función para imprimir en el main, los resultados.



    */
public static String Calcular_empaque(int bombillas){
        try {
            int cajas_necesito=0, bom_sin_emp=0, contador=1;
            double pallets_necesito=0, redondeo_pallets=0;
            final int  treinta=30, dieciseis=16;
            String resultado="";

            cajas_necesito= bombillas/treinta;
            bom_sin_emp= (bombillas)-(cajas_necesito*treinta);
            pallets_necesito= cajas_necesito/(double)dieciseis;
            redondeo_pallets= (int)(Math.ceil(pallets_necesito));


           
            resultado = "Para "+ bombillas+ " bombillas, se necesitan "+ cajas_necesito+ " cajas y "+ redondeo_pallets+" pallets. Se quedan "
            + bom_sin_emp+ " bombillas sin empacar. Se empacará así: \n\n";

            for(int pallet=1; pallet <=redondeo_pallets; pallet++){
                resultado += "Pallet "+ pallet+ " --> ";

                for(int caja=1; caja<= dieciseis && contador<=cajas_necesito; caja++){
                    resultado+= "Caja"+contador;
                    contador++;
                    
                    if (caja <= dieciseis - 1 && contador <= cajas_necesito)
                        resultado+=", ";
                    

                }
                resultado+="\n";
            }
            return resultado;

        } 
        catch (Exception e) {
            return "error" +e;
        }
    }


    

    /* 
    

        4.	En un juego, cada jugador tiene 3 intentos para sacar cartas de una baraja. Las cartas van numeradas entre 1 y 10. 
        Una función Jugar_21, deberá simular el juego para una cantidad de usuarios que enviará el usuario desde el main entre 1 y 6.

        Para cada uno de los jugadores, el programa le calculará 3 cartas al azar y al final imprimirá el juego para cada jugador basado en las siguientes reglas: 
        
        Si saca 21 exactos: juego perfecto
        Si saca más de 21: se pasó
        Si saca menos de 21: faltaron puntos

        La función deberá imprimir los puntos de cada jugador junto con la regla anterior, como muestra el ejemplo:

        Jugador X, puntos 21 -- > juego perfecto
        Jugador Y, puntos 26 -- > se pasó
        .
        .


    */
public static String Jugar_21(byte jugadores){
        try {
            String respuesta="";
            byte ale1=0, ale2=0, ale3=0, aleatorio=0, suma=0;
            final byte num_max=6, tres=3, diez=10, uno=1, dos=2, veinte_uno=21;
            

            respuesta += " Si saca 21 exactos: juego perfecto \n Si saca más de 21: se pasó \n Si saca menos de 21: faltaron puntos \n";

            if(jugadores < uno && jugadores > num_max)
                return "No se puede evaluar si hay menos de 1 jugador y mas de 6 jugadores";
            else{
                for(byte jug=1; jug <= jugadores; jug++){
                    
                    
                    ale1=(byte)(Math.random()*(diez)+uno);
                        ale2=(byte)(Math.random()*(diez)+uno);
                        ale3=(byte)(Math.random()*(diez)+uno);
                        suma=(byte)(ale1+ale2+ale3);

                        respuesta+= "Jugador "+ jug + ", "+"puntos "+ suma;

                    if (suma ==veinte_uno)
                        respuesta+= " -- > juego perfecto \n";
                    else if (suma > veinte_uno)
                        respuesta+=" -- > se pasó \n";
                    else 
                        respuesta+= " -- > faltaron puntos \n";
                }
            }

            return respuesta;

        } catch (Exception e) {
            return "error " +e;
        }
    }


}
